// Workspace-related channels
const WORKSPACE_PREFIX = 'WORKSPACE';
exports.CREATE_WORKSPACE = `${WORKSPACE_PREFIX}/CREATE`;
exports.GET_ALL_WORKSPACES = `${WORKSPACE_PREFIX}/GET_ALL`;
exports.GET_WORKSPACE = `${WORKSPACE_PREFIX}/GET`;
exports.DELETE_WORKSPACE = `${WORKSPACE_PREFIX}/DELETE`;
exports.EDIT_WORKSPACE = `${WORKSPACE_PREFIX}/EDIT`;
exports.RUN_WORKSPACE = `${WORKSPACE_PREFIX}/RUN`;
exports.STOP_WORKSPACE = `${WORKSPACE_PREFIX}/STOP`;
