// Workspace-related channels
const WORKSPACE_PREFIX = 'WORKSPACE';
exports.CREATE_WORKSPACE = `${WORKSPACE_PREFIX}/CREATE`;
exports.GET_ALL_WORKSPACES = `${WORKSPACE_PREFIX}/GET_ALL`;
exports.GET_WORKSPACE = `${WORKSPACE_PREFIX}/GET`;
exports.DELETE_WORKSPACE = `${WORKSPACE_PREFIX}/DELETE`;
exports.EDIT_WORKSPACE = `${WORKSPACE_PREFIX}/EDIT`;
exports.RUN_WORKSPACE = `${WORKSPACE_PREFIX}/RUN`;
exports.STOP_WORKSPACE = `${WORKSPACE_PREFIX}/STOP`;
exports.GET_ALL_ROUTES_WORKSPACE = `${WORKSPACE_PREFIX}/GET_ALL_ROUTES`;

// Route Group
const ROUTE_GROUP_PREFIX = 'ROUTE_GROUP';
exports.CREATE_ROUTE_GROUP = `${ROUTE_GROUP_PREFIX}/CREATE`;
exports.DELETE_ROUTE_GROUP = `${ROUTE_GROUP_PREFIX}/DELETE`;
exports.EDIT_ROUTE_GROUP = `${ROUTE_GROUP_PREFIX}/EDIT`;
exports.CHANGE_ORDER_ROUTE_GROUP = `${ROUTE_GROUP_PREFIX}/CHANGE_ORDER`;

// Route
const ROUTE_PREFIX = 'ROUTE';
exports.CREATE_ROUTE = `${ROUTE_PREFIX}/CREATE`;
exports.DELETE_ROUTE = `${ROUTE_PREFIX}/DELETE`;
exports.EDIT_ROUTE = `${ROUTE_PREFIX}/EDIT`;
exports.CHANGE_ORDER_ROUTE = `${ROUTE_PREFIX}/CHANGE_ORDER`;
